### ISSUE TITLE
Nicer landing page

### ISSUE THREAD

**Issue by ayushjainrksh** [apertium/apertium-apy#124] opened 2019-02-19 13:18 UTC
When running apertium-html-tools using `docker-compose up`, if I try to visit localhost:2737/ it takes me to http://wiki.apertium.org/wiki/Apertium-apy. Visiting this route should show a status page with a link to wiki.

**Comment by sushain97** [comment] 2019-02-19 20:09
This is the intended behavior. I'd rather not have APy serve any complex HTML. Moreover, having the redirect work is already saying that APy is up (i.e. its status).

**Comment by unhammer** [comment] 2019-02-19 20:40
I find the redirect a bit annoying and confusing.

I agree it shouldn't serve complex html, but it's not very complex to just say "this is apy, here are the docs"

**Comment by sushain97** [comment] 2019-02-19 20:42
Ideally, it would serve the swagger HTML/JS like stats-service:

http://apertium.projectjj.com/stats-service/

Alas, until then ~10 lines of unstyled HTML is fine with me.

**Comment by utkarsh-raj** [comment] 2019-02-20 09:32
Can I be assigned to the task @sushain97 ?

**Comment by unhammer** [comment] 2019-02-20 09:37
Anyone's free to create a pull request

**Comment by utkarsh-raj** [comment] 2019-02-20 09:39
Great, I will try to reproduce and look into it. Thanks.

**Closed** 2019-03-05 06:07 UTC
Labels: enhancement, help wanted
