### ISSUE TITLE
Support Mainline Distro Dependencies

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-apy#99] opened 2018-03-27 11:02 UTC
APy should support a much wider range of dependencies, most important being the ones you can get via apt-get on the various supported distros. PyPi isn't enough: https://github.com/apertium/apertium-apy/pull/91#issuecomment-376473818

E.g., for python3-tornado this means a range of versions in [Debian](https://packages.debian.org/search?keywords=python3-tornado) and [Ubuntu](https://packages.ubuntu.com/search?keywords=python3-tornado) that comes out to:
3.1 (trusty)
3.2 (jessie)
4.2 (xenial)
4.4 (stretch)
4.5 (artful+bionic)
5.0 (buster+sid)

We can cut away old versions, such as dropping support for 3.x (trusty+jessie), but future versions will keep happening and must work.

**Comment by sushain97** [comment] 2018-03-27 12:42
I don't think it's worth supporting 3.1 and 3.2. 4.2 may be supported in rc2 but I'll need to verify that this evening. If it is, I'll drop the requirements in setup.py and requirements.txt so that CI runs against 4.2. Supporting 5.0 is a separate concern I might have time to look into...

**Comment by sushain97** [comment] 2018-03-27 15:59
Continuing discussion from #91: given that APy completely breaks on Tornado 5.0, the ceiling requirement is here to stay until the issue is fixed in APy. At least this way, PyPi consumers won't get a broken package.

**Comment by sushain97** [comment] 2018-03-28 00:13
Didn't require any changes to fix for 4.2 (xenial). Released on PyPi and tagged as `v0.11.0.rc3`.

**Comment by sushain97** [comment] 2018-04-01 16:03
https://github.com/apertium/apertium-apy/pull/102 may fix 5.0. Waiting for go-ahead from @unhammer.

**Comment by TinoDidriksen** [comment] 2018-04-03 09:34
On latest Debian Sid, with `python3-tornado (5.0.0-2)` installed, I get:

````
apertium_apy.handlers (unittest.loader._FailedTest) ... ERROR
...
  File ".../apertium_apy/handlers/base.py", line 15, in <module>
    class BaseHandler(tornado.web.RequestHandler):
AttributeError: module 'tornado' has no attribute 'web'
````

**Comment by sushain97** [comment] 2018-04-03 13:36
Unfortunately, I'm unable to repro the problem.

**Comment by sushain97** [comment] 2018-04-04 03:54
https://github.com/apertium/apertium-apy/issues/84 is now the real problem. Conversation is on IRC regarding it.

**Closed by sushain97** 2018-04-04 03:54 UTC
Labels: enhancement
